name: brilliant_sdk
description: Brilliant SDK - Flutter package for Brilliant Labs Halo and Frame devices
version: 0.1.0
homepage: https://github.com/brilliantLabsAR/brilliant_sdk_flutter

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  frame_ble: ^3.0.0
  frame_msg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter