#!/usr/bin/env python3
"""Regenerate the EXAMPLES.md indexes for the Python and Flutter example sets.

The indexes are derived, not hand-maintained: Python entries come from each
example's one-line module docstring (plus the device-side Lua file(s) it
uploads), Flutter entries from the first paragraph of each app's README.
To change a description, edit the docstring/README and re-run:

    python3 tools/generate_example_indexes.py

Exits nonzero if any example lacks a docstring/README so gaps get noticed.
"""

import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

GENERATED_NOTE = (
    "<!-- Generated by tools/generate_example_indexes.py — edit the example "
    "docstrings/READMEs, not this file. -->"
)

PAIRING_NOTE = (
    "Most examples are two files: the host-side Python program here and a "
    "device-side Lua app (in `lua/`) that it uploads with `upload_frame_app()` "
    "after uploading the standard Lua libraries. The two sides pass messages "
    "identified by a single-byte message code, so the codes in the Python and "
    "Lua files must match exactly."
)

# Bring-up / calibration / measurement scripts, as opposed to teaching examples.
MSG_DIAGNOSTICS = {
    "compare_alignments",
    "imu_calibrate",
    "imu_diagnostic",
    "imu_direction_verify",
}

# One-shot device management scripts, as opposed to teaching examples.
BLE_UTILITIES = {
    "clear_display",
    "halo_fetch_logs",
    "halo_standby",
    "ota_flash",
    "reset_palette",
    "send_break",
    "send_remove",
    "send_reset",
    "stay_awake_false",
    "stay_awake_true",
}

problems: list[str] = []


def first_docstring_line(py: Path) -> str | None:
    doc = ast.get_docstring(ast.parse(py.read_text()))
    if not doc:
        return None
    para: list[str] = []
    for line in doc.strip().splitlines():
        line = line.strip()
        if not line:
            break
        para.append(line)
    return " ".join(para)


def lua_refs(py: Path) -> list[str]:
    refs = re.findall(r"lua/([\w./]+?\.lua)", py.read_text())
    seen: list[str] = []
    for r in refs:
        base = r.replace(".min.lua", ".lua")
        if base not in seen:
            seen.append(base)
    return seen


def python_rows(examples_dir: Path) -> list[tuple[str, str, str]]:
    rows = []
    for py in sorted(examples_dir.glob("*.py")):
        desc = first_docstring_line(py)
        if desc is None:
            problems.append(f"{py.relative_to(REPO)}: no module docstring")
            desc = "_(no description — add a module docstring)_"
        rows.append((py.name, ", ".join(f"`{r}`" for r in lua_refs(py)), desc))
    return rows


def emit_python_index(examples_dir: Path, title: str, intro: str,
                      groups: list[tuple[str, set[str] | None]]) -> None:
    rows = python_rows(examples_dir)
    grouped: dict[str, list[tuple[str, str, str]]] = {name: [] for name, _ in groups}
    default_group = groups[0][0]
    for row in rows:
        stem = row[0][:-3]
        target = default_group
        for name, members in groups:
            if members and stem in members:
                target = name
        grouped[target].append(row)

    out = [f"# {title}", "", GENERATED_NOTE, "", intro, ""]
    for name, _ in groups:
        if not grouped[name]:
            continue
        out += [f"## {name}", "", "| Example | Device-side Lua | Description |",
                "|---|---|---|"]
        out += [f"| [`{f}`](./{f}) | {lua} | {desc} |" for f, lua, desc in grouped[name]]
        out.append("")
    (examples_dir / "EXAMPLES.md").write_text("\n".join(out))
    print(f"wrote {examples_dir.relative_to(REPO)}/EXAMPLES.md ({len(rows)} examples)")


def flutter_index(example_dir: Path) -> None:
    rows = []
    for app in sorted(p for p in example_dir.iterdir() if p.is_dir()):
        readme = app / "README.md"
        if not readme.exists():
            problems.append(f"{app.relative_to(REPO)}: no README.md")
            rows.append((app.name, "_(no README)_"))
            continue
        desc = None
        para: list[str] = []
        for line in readme.read_text().splitlines():
            line = line.strip()
            if para and not line:
                break
            if not line or line.startswith(("#", "!", "<", "[![")):
                continue
            para.append(line)
        if para:
            desc = " ".join(para)
        if desc is None:
            problems.append(f"{readme.relative_to(REPO)}: no description paragraph")
            desc = "_(no description in README)_"
        rows.append((app.name, desc))

    out = [
        "# simple_brilliant_app example apps",
        "",
        GENERATED_NOTE,
        "",
        "Complete Flutter apps built on `simple_brilliant_app` (which wraps the "
        "connect / upload / run lifecycle). Each directory is a runnable app "
        "with its own README and, where needed, a device-side Lua app under "
        "`assets/`.",
        "",
        "| App | Description |",
        "|---|---|",
    ]
    out += [f"| [`{name}`](./{name}/) | {desc} |" for name, desc in rows]
    out.append("")
    (example_dir / "EXAMPLES.md").write_text("\n".join(out))
    print(f"wrote {example_dir.relative_to(REPO)}/EXAMPLES.md ({len(rows)} apps)")


def main() -> int:
    emit_python_index(
        REPO / "python/packages/brilliant_msg/examples",
        "brilliant-msg examples (Python)",
        "Host-side examples for the `brilliant-msg` message layer on Brilliant "
        "Labs glasses (Halo and Frame).\n\n" + PAIRING_NOTE,
        [("Examples", None), ("Tools & diagnostics", MSG_DIAGNOSTICS)],
    )
    emit_python_index(
        REPO / "python/packages/brilliant_ble/examples",
        "brilliant-ble examples (Python)",
        "Examples for the low-level `brilliant-ble` BLE layer: sending Lua "
        "directly to the device REPL, uploading files, and device management. "
        "No message-layer protocol involved — see the `brilliant_msg` examples "
        "for the higher-level app pattern.",
        [("Examples", None), ("Device utilities", BLE_UTILITIES)],
    )
    flutter_index(REPO / "flutter/packages/simple_brilliant_app/example")

    if problems:
        print("\nMissing descriptions:", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
